import BodyIllusTitleBodyLayout from "~/components/layout/BodyIllusTitleBodyLayout";
import BodyLightBlueBg from "~/components/layout/BodyLightBlueBg";
import MainLightBlueBg from "~/components/layout/MainLightBlueBg";
import MainTitleCaptionBodyLayout from "~/components/layout/MainTitleCaptionBodyLayout";
import SecondaryBlueBg from "~/components/layout/SecondaryBlueBg";
import TechIcon from "~/components/TechIcon";
import Fido2Project from "../assets/images/Fido2Project.png";
import AndroidIcon from "../assets/images/techIcon/Android.png";
import AppleIcon from "../assets/images/techIcon/Apple.png";
import ReactJsIcon from "../assets/images/techIcon/React.png";
import NodeJsIcon from "../assets/images/techIcon/NodeJS.png";
import JavaIcon from "../assets/images/techIcon/Java.png";
import DocumentationIcon from "../assets/images/Documentation.png";
import SequenceDiagramIcon from "../assets/images/SequenceDiagram.png";

export default function Fido2Proj() {
  return (
    <>
      <MainLightBlueBg>
        <MainTitleCaptionBodyLayout
          mainTitleLineOne="Designing and implementing"
          mainTitleLineTwo='FIDO2 in corporate app'
          date='September 2023'
          body='The FIDO2 protocol or sometimes being known as webauthn, is a passwordless authentication protocol set by the FIDO alliance. We brings it one step forward by using it as transaction authentication instead of only utilising the device’s biometric verification.'
        />

        <div className="">
          <img src={Fido2Project} alt="Fido2Project" />
        </div>
      </MainLightBlueBg>

      <SecondaryBlueBg>
        <BodyIllusTitleBodyLayout
          illus={
            <div className="grid grid-rows-1 grid-cols-3 gap-2">
              <TechIcon
                key='React'
                techName='React Native'
                imgSrc={ReactJsIcon}
              />
              <TechIcon
                key='Android'
                techName='Android'
                imgSrc={AndroidIcon}
              />
              <TechIcon
                key='iOS'
                techName='iOS'
                imgSrc={AppleIcon}
              />
            </div>
          }
          title='Built a FIDO2 CTAP library in React Native and native Android and iOS'
          body='I have developed a React Native library for FIDO2 CTAP (Client to Authenticator Protocol) that facilitates communication between the app (client) and the authenticator (platform authenticator). The code is written natively in both Java and Swift and then bridged to React Native. The library is designed to be user-friendly, with a payload following a specific structure. It will respond with the FIDO2 response, and a FIDO2 key pair will be generated as well.'
        />
      </SecondaryBlueBg>

      <BodyLightBlueBg>
        <BodyIllusTitleBodyLayout
          illus={
            <div className="grid grid-rows-1 grid-cols-2 gap-2">
              <TechIcon
                key='NodeJs'
                techName='NodeJs'
                imgSrc={NodeJsIcon}
              />
              <TechIcon
                key='Java'
                techName='Java'
                imgSrc={JavaIcon}
              />
            </div>
          }
          title='Implemented server side library'
          body='FIDO2 necessitates a server-side function to verify the response generated by FIDO2 CTAP. The goal is to ascertain whether the signature can be authenticated by the public key linked to the user stored in the database, particularly in the context of authentication. I have utilized open-source libraries in both NodeJS and Java to develop these functions, and they have been successfully validated.'
        />
      </BodyLightBlueBg>

      <SecondaryBlueBg>
        <BodyIllusTitleBodyLayout
          illus={
            <img src={DocumentationIcon} alt="Documentation Illustration" className="w-36" />
          }
          title='Written a 70 pages documentation'
          body='In order to ensure proper usage and understanding by developers utilizing the library as well as the server-side code, I have authored a 70-page documentation. This documentation includes illustrations and example codes to aid comprehension. I firmly believe that comprehensive documentation is essential for maintaining code integrity.'
        />
      </SecondaryBlueBg>

      <BodyLightBlueBg>
        <BodyIllusTitleBodyLayout
          illus={
            <img src={SequenceDiagramIcon} alt='SequenceDiagram Illustration' className="w-44" />
          }
          title='Designed implementation architecture'
          body='Since the FIDO2 implementation is entirely new to our company, I have dedicated time to studying the FIDO2 sequence diagram. From this study, I have developed an implementation architecture tailored to suit our company app use case. This process includes creating sequence diagrams and presenting them to superiors for feedback and review. Ultimately, this collaborative effort results in a finalized plan for implementation.'
        />
      </BodyLightBlueBg>
    </>
  )
}